### ISSUE TITLE
Need Ruby 2.2 specs

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3264]
Pulled from the [NEWS](https://github.com/ruby/ruby/blob/v2_2_0_preview1/NEWS) file

* nil/true/false
  - [x] nil/true/false objects are frozen - spec: 0d0d809c292b7e1a2ed66479f0b227a5fce17f9e & implementation: 6580956db009c0e376ead78067639d40d56adaf7

* Binding
  * New methods:
    - [x] Binding#local_variables - spec: 81b9f5d6bbfa6b8df8ab722098981f2856b07a7d & implementation: 32f555ef9a198e5a519fd5c1cf70024cb05d5eb1
    - [x] Binding#receiver - spec: 0c9027b8d4705481d641422cdcc13e031a91f7cf & implementation: 32f555ef9a198e5a519fd5c1cf70024cb05d5eb1

* Dir
  * New methods:
    - [x] Dir#fileno - spec: 96d033d303b0ea6aa3b661523556f4bb87156829, 2958f37ffe8cf620bbd23e3a0c1b1f1872592b43 & implementation: 7111811f6456daea686de6f0adafa3dacdd3f3ed

* Enumerable
  * New methods:
    - [x] Enumerable#slice_after - spec: 73496c350473a05b721745bea0cd8ca4da9fb71b & implementation: 6590ec7b285ad1a87651ee17f096f95de2b7eb94
    - [x] Enumerable#slice_when - spec: 9ebed9ab6d5ba704977342d0f77ea933550868b3 & implementation: f21d58d735383a30156575a2c51b0982b6bae217
  * Extended methods:
    - [x] min (supports optional argument to return multiple elements) - spec: 47f8941210f39daf0bb4f6ecee8a05dde689afbd & implementation: #3420
    - [x] min_by (supports optional argument to return multiple elements) - spec: 56cd372e68d1477d6938a6162a6521a983fa0eb6, 17f2186d47f9f1ad9bba36aee232deeb60a7d2c2 & implementation: #3420
    - [x] max (supports optional argument to return multiple elements) - spec: ef33bafa58594989851ca864cb63afa51e540700 & implementation: #3420
    - [x] max_by (supports optional argument to return multiple elements) - spec: a8d91ea46ebf667477bcab849efb7dc638b52616, 17f2186d47f9f1ad9bba36aee232deeb60a7d2c2 & implementation: #3420

* Float
  * New methods:
    - [x] Float#next_float - spec: 952991eb7103d802d62bde80377c63959fd4a300 & implementation: 8681c49c77e034619112d262cb5b8d055c7d167d
    - [x] Float#prev_float - spec: 952991eb7103d802d62bde80377c63959fd4a300 & implementation: 8681c49c77e034619112d262cb5b8d055c7d167d

* File
  * New methods:
    - [x] File.birthtime - spec: fb9049a35033fe91b1d4b22c9a40edb1b76df68a & implementation: 32bc2c6a73ca0e233f65ab1f20cf483812701f53
    - [x] File#birthtime - spec: fb9049a35033fe91b1d4b22c9a40edb1b76df68a & implementation: 32bc2c6a73ca0e233f65ab1f20cf483812701f53

* File::Stat
  * New methods:
    - [x] File::Stat#birthtime - spec: a85ab72ab8d1465f1d3c2404d3918edda023ffa7 & implementation: 32bc2c6a73ca0e233f65ab1f20cf483812701f53

* Kernel
  * New methods:
    - [x] Kernel#itself - spec: 73ddfc2c174034bef36a86726c2af4ca253d2868 & implementation: 73ddfc2c174034bef36a86726c2af4ca253d2868
  * Improvements
    - [x] Kernel#throw raises UncaughtThrowError, subclass of ArgumentError when
      there is no corresponding catch block, instead of ArgumentError. - spec: 89072dbb28ace14cea11818a484275eb6c916b23 & implementation: 697d16891b69a4d5b60d65332170836fcd8ffcb0

* Process
  * Extended method:
    - [x] Process execution methods such as Process.spawn opens the file in write mode for redirect from [:out, :err].
    - [x] ~~Process creation methods, such as spawn(), uses vfork() system call. vfork() is faster than fork() when the parent process uses huge memory.~~

* String
  * New methods:
    - [x] String#unicode_normalize
    - [x] String#unicode_normalize!
    - [x] String#unicode_normalized?

* Symbol
  - [x] ~~Add syntax for `{ "abc": 123 }`~~ Moved to https://github.com/rubinius/rubinius/issues/3600
  * Improvements
    - [x] ~~Most symbols which are returned by String#to_sym and String#intern are GC-able.~~ Moved to https://github.com/rubinius/rubinius/issues/3599
    - [x] ~~To spec GC'd Symbol, a possible spec uses `ObjectSpace.each_object(Symbol)`~~

* Method
  * New methods:
    - [x] Method#curry([arity]) returns a curried Proc. - spec: 0bc0390ba2137ee266f7fe816ee583d0e805848a & implementation: 6304e7dfb557a452099f23659657882ecd7cf4ce
    - [x] Method#super_method returns a Method of superclass, which would be called when super is used. - spec: 4d34db2806df68580f6799e3d1caea99be29d957

**Comment by tak1n** [comment]
@nirvdrum mentioned following in #3401 :

"It looks like in MRI 2.2+, nil is now frozen. I looked at making things match, but it creates problems in common/kernel.rb:175. If nil is frozen, that line prevents extending it with a module, but that should be allowed. I think it can be safely removed, since object_extend should catch any issues. But I'd appreciate feedback from someone more familiar with things before proceeding."

**Comment by chuckremes** [comment]
The "nil/true/false" objects are frozen spec and implementation are done. There is also a side effect as mentioned by @tak1n above where methods can be added to those three objects *even though* they are frozen. That has also been implemented by  a2d76f so no need to work on those anymore.

**Comment by YorickPeterse** [comment]
I cleaned up https://github.com/rubysl/rubysl-unicode_normalize a bit (license wise and such), pushed it to RubyGems and updated the rubysl Gem to depend on it. In 7489a077960dabf9a5d26cb638a7cc5476ed1828 I made sure we're actually shipping these changes.

@brixen The unicode normalization code is loaded by default on MRI. Do we have a proper way to load a Gem during bootup? I suspect just dumping a `require` in the kernel code could break things.

**Comment by YorickPeterse** [comment]
@tak1n In 008cd1ebc0257c51b0dd0676dc0b955a1aa6ea8c you added specs for redirecting output for `Process.spawn`. These specs currently seem to pass, are they related to the `Process.spawn` changes mentioned in the release notes?

**Comment by tak1n** [comment]
@YorickPeterse I don't remember it exactly anymore, I'll take a closer look on it what exactly changed on MRI side and see if our behaviour currently is the same and the spec is ensuring this.

**Comment by tak1n** [comment]
@YorickPeterse The redirection thing in Process#spawn is kinda confusing right now for me, but I used this script for testing:

```ruby
spawn(RbConfig.ruby, "-eSTDERR.print :glark", :out => ["test", "w"], :err => [:child, :out])
```

Both MRI 2.2.4 and RBX 3.11.c7 are writing "glark" into a file called "test".
So I think this spec was here to ensure this behavior. Oddly enough I can't see anything which changed in the kernel code regarding for it, so it already behaved that way.

**Comment by YorickPeterse** [comment]
@tak1n Thanks. In that case I'll just mark it as fixed. If it turns out to be otherwise we can fix it whenever brought up.

**Comment by tak1n** [comment]
@YorickPeterse  Oddly enough also MRI 2.1.7 behaves that way.
```
~ ❯❯❯ ruby -v
ruby 2.1.7p400 (2015-08-18 revision 51632) [x86_64-linux]
~ ❯❯❯ cat test.rb
spawn(RbConfig.ruby, "-eSTDERR.print :glark", :out => ["test", "w"], :err => [:child, :out])
~ ❯❯❯ ruby test.rb
~ ❯❯❯ cat test
glark%
```

**Comment by YorickPeterse** [comment]
Checked off vfork usage as well. While interesting this isn't really something exposed to Ruby and I don't think it's really worth our time at this point. Maybe in the future it's interesting but we should open a dedicated issue in that case.

**Comment by YorickPeterse** [comment]
Moved remaining TODOs to separate issues, closing this one.
