### ISSUE TITLE
Need Ruby 2.3 specs

### ISSUE THREAD

**Issue by chuckremes** [rubinius/rubinius#3559]
Pulled from Ruby [News](https://github.com/ruby/ruby/blob/trunk/doc/NEWS-2.3.0)

### Language changes

* frozen-string-literal pragma:

  - [x] ~~new pragma, frozen-string-literal has been experimentally introduced.
    [Feature #8976](https://bugs.ruby-lang.org/issues/8976)~~
  - [x] ~~besides, --enable/--disable=frozen-string-literal options also have
    been introduced. [Feature #8976](https://bugs.ruby-lang.org/issues/8976)~~
  - [x] ~~command line options --debug or --debug=frozen-string-literal enable
    additional debugging mode which shows created location with at frozen
    object error (RuntimeError).
    [Feature #11725](https://bugs.ruby-lang.org/issues/11725)~~

We're not going to port over MRI's weird String hacks, we can either make the compiler smarter (removing the need for developers to add anything) or have the JIT optimize code where needed.

* safe navigation operator:

  - [x] new method call syntax, `object&.foo', method #foo is called on
    `object' if it is not nil.
    this is similar to `try!' in Active Support, except:
    - [x] method name is syntactically required
          obj.try! {} # valid
          obj&. {}    # syntax error
    - [x] arguments are evaluated only if a call is made:
          obj.try!(:foo, bar())  # bar() is always evaluated
          obj&.foo(bar())        # bar() is conditionally evaluated
    - [x] attribute assignment is valid
          obj&.attr += 1
    [Feature #11537](https://bugs.ruby-lang.org/issues/11537) Moved to https://github.com/rubinius/rubinius/issues/3601

* the did_you_mean gem:

  - [x] ~~When a NameError or NoMethodError occurs because of a typo in the name,
    the did_you_mean gem automatically suggests other names similar to the
    method name.~~ People can just install this Gem themselves

      "Yuki".starts_with?("Y")
      # => NoMethodError: undefined method `starts_with?' for "Yuki":String
      #    Did you mean?  start_with?

* indented here document:

  - [x] new string literal, here document starts with `<<~`.
    refer doc/syntax/literals.rdoc for more details.
    [Feature #9098](https://bugs.ruby-lang.org/issues/9098) Moved to https://github.com/rubinius/rubinius/issues/3602

### Core classes updates (outstanding ones only)

* ARGF

  - [x] ARGF.read_nonblock supports `exception: false' like IO#read_nonblock.
    [Feature #11358](https://bugs.ruby-lang.org/issues/11358) 391db8d72bc9227a191d181dd76d17a4715e6f16

* Array

  - [x] Array#bsearch_index [Feature #10730](https://bugs.ruby-lang.org/issues/10730): https://github.com/rubinius/rubinius/pull/3566
  - [x] Array#dig [Feature #11643](https://bugs.ruby-lang.org/issues/11643) #3562

* Comparable

  - [x] Comparable#== no longer rescues exceptions [Feature #7688](https://bugs.ruby-lang.org/issues/7688): https://github.com/rubinius/rubinius/pull/3574

* Encoding

  - [x] new Encoding::IBM037 (alias ebcdic-cp-us; dummy) Moved to https://github.com/rubinius/rubinius/issues/3603

* Enumerable

  - [x] Enumerable#grep_v is added as inverse version of Enumerable#grep.
    [Feature #11049](https://bugs.ruby-lang.org/issues/11049): #3575
  - [x] Enumerable#chunk_while [Feature #10769](https://bugs.ruby-lang.org/issues/10769): #3579

* Enumerator::Lazy

  - [x] Enumerator::Lazy#grep_v [Feature #11773](https://bugs.ruby-lang.org/issues/11773): #3577

* File

  - [x] File.mkfifo [Feature #11536](https://bugs.ruby-lang.org/issues/11536): #3578
  - [x] ~~Add File::TMPFILE corresponding to O_TMPFILE~~ Requires GNU/glibc extensions, last time I tried enabling these it broke a lot.

* Hash

  - [x] Hash#fetch_values [Feature #10017](https://bugs.ruby-lang.org/issues/10017): e2d3a30b
  - [x] Hash#dig [Feature #11643](https://bugs.ruby-lang.org/issues/11643) #3562: 349c339
  - [x] Hash#<=, Hash#<, Hash#>=, Hash#> [Feature #10984](https://bugs.ruby-lang.org/issues/10984): 349c339
  - [x] Hash#to_proc [Feature #11653](https://bugs.ruby-lang.org/issues/11653): https://github.com/rubinius/rubinius/pull/3568

* IO

  - [x] ~~new mode flag File::SHARE_DELETE is available.
    this flag means to permit deleting opened file on Windows, but currently
    this affect only files opened as binary.  [Feature #11218](https://bugs.ruby-lang.org/issues/11218)~~ Windows specific, which we don't support at the moment.

  - [x] new option parameter `flags' is added.
    this parameter is bitwise-ORed to oflags generated by normal mode argument.
    [Feature #11253](https://bugs.ruby-lang.org/issues/11253) Moved to https://github.com/rubinius/rubinius/issues/3604

  - [x] IO#advise no longer raises Errno::ENOSYS in cases where it was
    detected at build time but not available at runtime.  [Feature #11806](https://bugs.ruby-lang.org/issues/11806) Moved to https://github.com/rubinius/rubinius/issues/3605

* Kernel

  - [x] Kernel#loop, when stopped by a StopIteration exception, returns
    what the enumerator has returned instead of nil. [Feature #11498](https://bugs.ruby-lang.org/issues/11498): https://github.com/rubinius/rubinius/pull/3572

* Module
  - [x] Module#deprecate_constant [Feature #11398](https://bugs.ruby-lang.org/issues/11398) Moved to https://github.com/rubinius/rubinius/issues/3606

* NameError
  - [x] NameError#receiver is added to take the receiver object. [Feature #10881](https://bugs.ruby-lang.org/issues/10881): Moved to https://github.com/rubinius/rubinius/issues/3607

* Numeric

  - [x] Numeric#positive? and Numeric#negative? are added, which return
    true when the receiver is positive and negative respectively.
    [Feature #11151](https://bugs.ruby-lang.org/issues/11151): #3564

* Proc

  - [X] ~~Proc#call (and also #[], #===, #yield) are optimized.
    Backtrace doesn't show each method (show block lines directly).
    TracePoint also ignores these calls. [Feature #11569](https://bugs.ruby-lang.org/issues/11569)~~ No, we'll either use proper compiler optimizations or the JIT. Not important for now.

* Queue (Thread::Queue)

  - [x] Queue#close is added to notice a termination. [Feature #10600](https://bugs.ruby-lang.org/issues/10600). Queue resides in rubysl-thread (https://github.com/rubysl/rubysl-thread/blob/2.0/lib/rubysl/thread/thread.rb) Moved to https://github.com/rubysl/rubysl-thread/issues/2

- [x] Regexp/String: Updated Unicode version from 7.0.0 to 8.0.0: Moved to https://github.com/rubinius/rubinius/issues/3615

* String

  - [x] String#+@ and String#-@ are added to get mutable/frozen strings.
    [Feature #11782](https://bugs.ruby-lang.org/issues/11782) Moved to https://github.com/rubinius/rubinius/issues/3608

  - [x] String.new now accepts new option parameter `encoding'.
    [Feature #11785](https://bugs.ruby-lang.org/issues/11785) https://github.com/rubinius/rubinius/pull/3583

* Struct
  - [x] Struct#dig [Feature #11688](https://bugs.ruby-lang.org/issues/11688) #3562

* Thread
  - [x] Thread#name, Thread#name= are added to handle thread names [Feature #11251](https://bugs.ruby-lang.org/issues/11251) Moved to https://github.com/rubinius/rubinius/issues/3609

### Core classes compatibility issues (excluding feature bug fixes)

* Array
  - [x] ~~Array#select!, Array#keep_if, Array#reject!, and Array#delete_if
    no longer changes the receiver array instantly every time the
    block is called.  [Feature #10714](https://bugs.ruby-lang.org/issues/10714)~~ We don't seem to suffer from this in the first place

  - [x] ~~Array#flatten and Array#flatten! no longer try to call #to_ary
    method on elements beyond the given level.  [Bug #10748](https://bugs.ruby-lang.org/issues/10748)~~ Doesn't appear to affect us

  - [x] Array#inspect doesn't raise error even if its content returns
    a string which is not compatible with Encoding.default_external
    as inspected result. [Feature #11801](https://bugs.ruby-lang.org/issues/11801) Moved to https://github.com/rubinius/rubinius/issues/3610

This can be reproduced using:

```ruby
o = Object.new

def o.inspect
  'abc'.encode(Encoding::UTF_32LE)
end

p [o].inspect
```

* Enumerable
  - [X] Enumerable#chunk and Enumerable#slice_before no longer takes the
    initial_state argument.  [Feature #10958](https://bugs.ruby-lang.org/issues/10958)
    Use a local variable instead to maintain a state.  #3580

* File::Stat
  - [x] ~~On Windows File::Stat#ino always returned 0, but now returns
    BY_HANDLE_FILE_INFORMATION.nFileIndexHigh/Low.  [Feature #11216](https://bugs.ruby-lang.org/issues/11216)~~ We don't support Windows at the moment

* Hash
  - [x] Hash#inspect doesn't raise error even if its content returns
    a string which is not compatible with Encoding.default_external
    as inspected result. [Feature #11801](https://bugs.ruby-lang.org/issues/11801) Moved to https://github.com/rubinius/rubinius/issues/3611

* IO
  - [X] IO#close doesn't raise when the IO object is closed.  [Feature #10718](https://bugs.ruby-lang.org/issues/10718) 0a0cd774b547ade71dff4a180b18528abeb5252a
  - [X] ~~IO#each_codepoint raises an exception at incomplete character
    before EOF when conversion takes place.  [Bug #11444](https://bugs.ruby-lang.org/issues/11444)~~ bug in question doesn't seem to affect us

* Module
  - [x] Module#define_method and Object.define_singleton_method now
    require method body, Proc, Method, or a block, and raise
    ArgumentError if no block is given directly.  [Bug #11283](https://bugs.ruby-lang.org/issues/11283) *Rubinius not affected*

* pack/unpack (Array/String)
  - [x] j and J directives for pointer width integer type.  [Feature #11215](https://bugs.ruby-lang.org/issues/11215) Moved to https://github.com/rubinius/rubinius/issues/3612

### C API updates

- [x] rb_define_class_id_under() now raises a TypeError exception when the
  class is already defined but its superclass does not match the given
  superclass, as well as definitions in ruby level. Moved to https://github.com/rubinius/rubinius/issues/3613

- [x] rb_timespec_now() is added to fetch current datetime as struct timespec.
  [Feature #11558](https://bugs.ruby-lang.org/issues/11558) Moved to https://github.com/rubinius/rubinius/issues/3614

- [x] rb_time_timespec_new() is added to create a time object with epoch,
  nanosecond, and UTC/localtime/time offset arguments.  [Feature #11558](https://bugs.ruby-lang.org/issues/11558) Moved to https://github.com/rubinius/rubinius/issues/3614

- [x] ~~rb_autoload() deprecated, use rb_funcall() instead.  [Feature #11664](https://bugs.ruby-lang.org/issues/11664)~~ We don't seem to have this function in the first place, yay

- [x] ~~rb_compile_error_with_enc(), rb_compile_error(), and rb_compile_bug()
  deprecated.  these functions are exposed but only for internal use.
  external libraries should not use them.~~ We don't have these any way

**Comment by brixen** [comment]
I edited the contents to use Markdown headings instead of RDoc headings.

A couple notes about this ticket:

1. As soon as the parser changes are in place so we can handle syntax like `&.`, we can update the compatibility version to 2.3.
2. As patches are applied to improve compatibility with 2.3, note the PR number or short commit SHA inline with the list item.
3. Regularly push releases with the new compatibility features. Anyone with commit rights can push a release by running `./scripts/tag.sh tag && git push --tags origin master` (I'll document this ASAP in [the Rubinius book](https://www.gitbook.com/book/rubinius/the-rubinius-book/).
4. Some things, like frozen Strings and Proc "optimization" we may not implement, so don't waste time on them. If a program runs on MRI with frozen Strings on, it can't be modifying them, so it really doesn't matter if they are not frozen, unless the program is specifically testing for that, which would be stupid. As for Proc, the Rubinius JIT can already optimize blocks by eliding them transparently and we'll likely expand the JIT capabilities over one-off hacks like the MRI "optimization".

**Comment by brixen** [comment]
Just added links to the Ruby Redmine tracker for all the features.

**Comment by YorickPeterse** [comment]
`File::TMPFILE` relies on `O_TMPFILE` which is only defined (at least on Linux) when `_GNU_SOURCE` is set. I've tried getting this to work in the past but it only ended up breaking things.

**Comment by YorickPeterse** [comment]
I moved all remaining TODOs to separate issues as that's much easier to keep track of. Closing this one.

**Comment by brixen** [comment]
@YorickPeterse thanks for making all those tickets. It was nice to have this ticket as an overview and an easy reference.
